name: Build

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: check
        run: ./gradlew check
