name: Build

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: check
        run: ./gradlew check
