name: Detekt

on:
  push:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: check
        run: ./gradlew detekt
