name: Detekt

on:
  push:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: check
        run: ./gradlew detekt
